---
title: "modis error"
author: "Ellie White"
date: "12/4/2020"
output: html_document
---

Record of downloading and bringing in MODIS data into R.

# Callbacks 
```{r callbacks}
# callback to add the time in the prompt, to avoid having to do a lot of profiling
# perhaps add this to R profile
h <- taskCallbackManager()
h$add(function(expr, value, ok, visible) { 
        options("prompt"=format(Sys.time(), "%H:%M:%S> ")); 
          return(TRUE)
        }, name = "simpleHandler"
      )
```

# MODIS ET Data
MODIS estimates Actual ET with Penman-Monteith.
```{r et}
library(rgdal)
library(raster)
library(dismo)
library(rgeos)

years <- 2008:2017
months <- c("01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12")
eighthdays <- c("001", "009", "017", "025", "033", "041", "049", "057", "065", "073", "081", 
"089", "097", "105", "113", "121", "129", "137", "145", "153", "161", "169", "177", "185", "193", "201", "209", "217", "225", "233", "241", "249", "257", "265", "273", "281", "289", "297", "305", "313", "321", "329", "337", "345", "353", "361")
tileH <- 10:11
tileV <- 4:5

# # instructions on: https://gis.stackexchange.com/questions/240611/acquiring-modis-data by sboysel
# devtools::install_github("MatMatt/MODIS", ref = "develop")
library(MODIS)
getProduct() # to see what is available

# set MODIS options: data directories, projection, resolution, etc.
dir.create("input data/MODIS/MOD16A2/raw", showWarnings = FALSE)
dir.create("input data/MODIS/MOD16A2/processed", showWarnings = FALSE)

MODISoptions(
  localArcPath = "input data/MODIS/MOD16A2/raw", # otherwise data goes in tempdir() folder
  outDirPath = "input data/MODIS/MOD16A2/processed",
  outProj = "+proj=longlat +datum=WGS84 +ellps=WGS84",
  pixelSize = 1,
  dlmethod = "wget",
  MODISserverOrder = c("LAADS", "LPDAAC") # something is broken with LPDAAC
)

# # downloading data requires authentication and registration at https://urs.earthdata.nasa.gov/home
# # run the following command once to generate a .netrc file for EarthData (LPDAAC) login credentials
# MODIS::EarthdataLogin()
# use getTile to find the tileH and tileV values

MODIS:::genString("MOD16A2")

# Download and process (stitch, reproject, dis / aggregate)
getHdf(
  product = "MOD16A2",
  collection = "006",
  begin = "2008.02.10",
  end = "2017.12.31",
  tileH = 10:11,
  tileV = 4:5
)

# example, maybe runGdal will work.
runGdal(
  product = "MOD16A2",
  collection = "006",
  begin = "2008.02.10",
  end = "2008.12.31",
  tileH = 10,
  tileV = 4
)

# list stitched MODIS products
modis_fp <- list.files(path = "input data/MODIS", pattern = ".hdf", recursive = TRUE, full.names = TRUE)

# need to process hdf4 to hdf5 first because the raster package can't read those files
library(gdalUtils)
gdal_setInstallation(verbose=TRUE)
getOption("gdalUtils_gdalPath")

# library(devtools)
# install_version("rgdal", version="1.3-1")

# # download gdal from: https://gdal.org/download.html and put in "C:/Users/white/Documents/R/win-library/4.0"
# gdal_setInstallation(ignore.full_scan=FALSE)

gdal.AllRegister()

gdalinfo(modis_fp[1])
sds <- get_subdatasets(normalizePath(paste0(getwd(),"/", modis_fp[1])))
# gdal_translate(sds[1], dst_dataset = "NPP2000.tif")

outfile <- paste0(getwd(),"/output data/")
gdal_translate(normalizePath(paste0(getwd(),"/", modis_fp[1])), outfile, sds=TRUE, verbose=TRUE)

# loading the first processed raster for demonstration
r <- raster::raster(x = modis_fp[1])

```








